import "server-only";

/**
 * PwnDoc YAML export (P1-H).
 *
 * PwnDoc (https://pwndoc.github.io) is an open-source pentest report
 * platform; it imports findings via YAML/JSON. Like the SysReptor export
 * this is a *generic shape* operators map onto their own audit templates
 * after import.
 *
 * Field mapping:
 *   - name       → engagement.name
 *   - date       → engagement.created_at (ISO date)
 *   - scope[]    → "<hostname> (<ip>)" or "<ip>"
 *   - findings[].title / severity / description / cve / affected
 *
 * YAML emission: hand-rolled minimal serializer (no js-yaml dep at this
 * layer — we already serialize a tightly-defined shape, and the helper
 * here gives us byte-stable output for tests). Strings that would be
 * ambiguous in YAML (containing `:`, `#`, leading whitespace, etc.) get
 * double-quoted with embedded `"`/`\` escaped.
 */

import type { EngagementViewModel } from "./view-model";

const SEVERITY_LABEL: Record<string, string> = {
  info: "Informational",
  low: "Low",
  medium: "Medium",
  high: "High",
  critical: "Critical",
};

/**
 * YAML scalar quote — wraps in `"..."` and escapes `\` + `"`. Numbers and
 * single-line strings without YAML-special characters can pass through
 * unquoted, but quoting unconditionally keeps the output deterministic
 * and avoids subtle parser ambiguities downstream.
 */
function yqs(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/** Indented block-list line: `${indent}- ${value}`. */
function bullet(indent: string, value: string): string {
  return `${indent}- ${value}`;
}

function multilineBlock(indent: string, value: string): string {
  // Use literal `|` block scalar so newlines in description survive.
  // Each continuation line is indented one level further than the key.
  const inner = `${indent}  `;
  const escaped = value
    .split(/\r?\n/)
    .map((line) => `${inner}${line}`)
    .join("\n");
  return `|\n${escaped}`;
}

export function generatePwndoc(vm: EngagementViewModel): string {
  // Build host-keyed port info.
  const portIndex = new Map<
    number,
    { port: number; protocol: string; hostLabel: string }
  >();
  const scope: string[] = [];
  for (const hvm of vm.hosts) {
    const hostLabel = hvm.host.hostname
      ? `${hvm.host.hostname} (${hvm.host.ip})`
      : hvm.host.ip;
    scope.push(hostLabel);
    for (const pvm of hvm.ports) {
      portIndex.set(pvm.port.id, {
        port: pvm.port.port,
        protocol: pvm.port.protocol,
        hostLabel,
      });
    }
  }
  if (scope.length === 0) {
    const primaryHost = vm.engagement.hosts[0];
    const fb = primaryHost?.hostname
      ? `${primaryHost.hostname} (${primaryHost.ip})`
      : primaryHost?.ip ?? vm.engagement.name;
    scope.push(fb);
    for (const pvm of vm.ports) {
      portIndex.set(pvm.port.id, {
        port: pvm.port.port,
        protocol: pvm.port.protocol,
        hostLabel: fb,
      });
    }
  }

  const lines: string[] = [];
  lines.push(`# Generated by recon-deck ${yqs(vm.recon_deck_version)}`);
  lines.push(`name: ${yqs(vm.engagement.name)}`);
  lines.push(`date: ${yqs(vm.engagement.created_at)}`);
  lines.push(`coverage_percent: ${vm.coverage}`);
  lines.push("scope:");
  for (const s of scope) lines.push(bullet("  ", yqs(s)));

  lines.push("findings:");
  for (const f of vm.engagement.findings) {
    lines.push(bullet("  ", `title: ${yqs(f.title)}`));
    lines.push(`    severity: ${yqs(SEVERITY_LABEL[f.severity] ?? f.severity)}`);
    if (f.cve) lines.push(`    cve: ${yqs(f.cve)}`);

    // Affected — list of "<host>:<port>/<proto>" or scope items.
    const affected: string[] = [];
    if (f.port_id != null) {
      const pi = portIndex.get(f.port_id);
      if (pi) affected.push(`${pi.hostLabel}:${pi.port}/${pi.protocol}`);
    }
    if (affected.length === 0) {
      for (const s of scope) affected.push(s);
    }
    lines.push("    affected:");
    for (const a of affected) lines.push(bullet("      ", yqs(a)));

    if (f.description && f.description.trim() !== "") {
      lines.push(`    description: ${multilineBlock("    ", f.description)}`);
    } else {
      lines.push(`    description: ${yqs("")}`);
    }
  }

  return lines.join("\n") + "\n";
}
